version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5
  nginx:
    build: ./urlshortener-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
